
version: 0.2

phases:
  install:
    on-failure: "ABORT"
    commands:
      - echo "no install phase"

  pre_build:
    commands:
      - echo "pre build"

  build:
    commands:
      - echo "build cf templates"

  post_build:
    commands:
      - echo "Post Build"

artifacts:
  files:
    - cloud/stack/*.yml

