
version: 0.2

phases:
  install:
    on-failure: "ABORT"
    commands:
      - apt update && apt -y upgrade
      - apt install jq

  pre_build:
    commands:
      - echo "pre build"

  build:
    commands:
      - jq -n --arg url $CF_STACK_BUCKET '{"GatewayTemplateUrl":$url}' > cloud/parameters.json

  post_build:
    commands:
      - echo "Post Build"

artifacts:
  files:
    - cloud/stack.yml
    - cloud/parameters.json
    - cloud/stack/*.yml

