
version: 0.2

phases:
  install:
    on-failure: "ABORT"
    commands:
      - echo "no install phase"

  build:
    commands:
      - echo "build cf templates"

  artifcts:
    files:
      - cloud/stack/*.yml

