AWSTemplateFormatVersion: "2010-09-09"
Description: "API used to manage EC2"


Resources:

  Gateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      Tags:
        - Key: "Application"
          Value: !Ref "AWS::StackName"

  GatewayStage:
    Type: "AWS::ApiGateway::Stage"
    Properties:
      RestApiId: !Ref "Gateway"
      StageName: "main"
      Tags:
        - Key: "Application"
          Value: !Ref "AWS::StackName"
