AWSTemplateFormatVersion: "2010-09-09"
Description: "API used to manage EC2"


Resources:

  Gateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      Tags:
        - Key: "Application"
          Value: !Ref "AWS::StackName"

  GatewayResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      PathPart: "myenv"
      RestApiId: !Ref "Gateway"

  MyEnvCreate:
    Type: "AWS::ApiGateway::Method"
    Properties:
      httpMethod: "POST"
      Type: "AWS"

  GatewayStageDeployment:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      RestApiId: !Ref "Gateway"

  GatewayStage:
    Type: "AWS::ApiGateway::Stage"
    Properties:
      RestApiId: !Ref "Gateway"
      StageName: "main"
      DeploymentId: !Ref "GatewayStageDeployment"
      Tags:
        - Key: "Application"
          Value: !Ref "AWS::StackName"
